---
# tasks file for deslicer.splunk.enterprise-install
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/deslicer)
#
# Release: 1.0.0

# tasks file for deslicer.splunk.enterprise-install
#
- name: Check Splunk status
  ansible.builtin.include_tasks: splunk_status.yml

- name: Include task to stage install files
  ansible.builtin.include_tasks: stage_install_files.yml
  when:
    - not stat_splunk_enterprise_bin.stat.exists or
      enterprise_upgrade | default(false)
    - not download_from_remote_file_storage | default(false)

- name: Include task to download install files
  ansible.builtin.include_tasks: download_install_files.yml
  when:
    - not stat_splunk_enterprise_bin.stat.exists or
      enterprise_upgrade | default(false)
    - download_from_remote_file_storage | default(false)

- name: Include task to ensure splunk version
  ansible.builtin.include_tasks: ensure_splunk_version.yml
  when:
    - not stat_splunk_enterprise_bin.stat.exists or
      enterprise_upgrade | default(false)

- name: Include task to always ensure that splunk is running
  ansible.builtin.include_tasks: ensure_splunk_status_started.yml
  when:
    - ensure_splunkd_started | default(true)

- name: Include task to inform that this host is managed by ansible
  ansible.builtin.include_tasks: ansible_managed.yml
  when:
    - not cca_splunk_enterprise_upgrade | default(false)
