---
# tasks file for deslicer.splunk_core
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1

- name: Wait for host connection
  ansible.builtin.wait_for_connection:
    timeout: "{{ cca_wait_for_connection_timeout | default('600') }}"
